export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_REFRESH_REUSE_DETECTED: 'AUTH_REFRESH_REUSE_DETECTED',
  AUTH_INVALID_OR_EXPIRED_RESET_TOKEN: 'AUTH_INVALID_OR_EXPIRED_RESET_TOKEN',
  AUTH_INVALID_CURRENT_PASSWORD: 'AUTH_INVALID_CURRENT_PASSWORD',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_CSRF_TOKEN_MISSING: 'AUTH_CSRF_TOKEN_MISSING',
  AUTH_CSRF_TOKEN_INVALID: 'AUTH_CSRF_TOKEN_INVALID',
  AUTH_LOGIN_LOCKED: 'AUTH_LOGIN_LOCKED',
  AUTH_USER_HAS_NO_ROLES: 'AUTH_USER_HAS_NO_ROLES',
  AUTH_MISSING_REQUIRED_ROLE: 'AUTH_MISSING_REQUIRED_ROLE',
  AUTH_MISSING_REQUIRED_PERMISSION: 'AUTH_MISSING_REQUIRED_PERMISSION',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_ROLE_REQUIRED: 'USER_ROLE_REQUIRED',
  USER_INVALID_ROLE: 'USER_INVALID_ROLE',
  ACCESS_DENIED: 'ACCESS_DENIED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DB_UNAVAILABLE: 'DB_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
