name: Feature request
description: Propose a reusable feature for future projects.
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What pain does this solve in real freelance projects?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the expected behavior and affected modules.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: List objective criteria to validate done-ness.
      placeholder: |
        - [ ] ...
        - [ ] ...
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Validation
      options:
        - label: This feature is generic enough to be reused in multiple client projects.
          required: true
